language: r
r:
 - 3.2
 - devel
cache: packages
warnings_are_errors: true
r_check_args: --as-cran

git:
  depth: 5

r_binary_packages:
 - testthat
  
r_packages:
 - covr
 - devtools
 - knitr
 - memoise
 - R.cache
 - rmarkdown
 - roxygen2
 - TreeSearch
   
install:
 - R -e "install.packages('devtools')"
 - R -e "install.packages('knitr')"
 - R -e "install.packages('phangorn')"
 - R -e "install.packages('rmarkdown')"
 - R -e "install.packages('roxygen2')"
 - R -e "install.packages('testthat')"
 - R -e "devtools::install_github('ms609/TreeSearch')"
 - R -e "devtools::document()"
  
after_success:
  - Rscript -e "install.packages('covr'); covr::codecov()"
  