language: r
r:
 - 3.4
 - devel
cache: packages
warnings_are_errors: true
r_check_args: --as-cran
env:
 - _R_CHECK_FORCE_SUGGESTS_=false

git:
  depth: 5

r_binary_packages:
 - testthat
 
r_packages:
 - covr
 - devtools
 - knitr
 - memoise
 - R.cache
 - rmarkdown
 - roxygen2
 - TreeSearch
 
r_github_packages:
 - ms609/Ternary
   
before_script:
 - R -e "devtools::document()"
  
after_success:
 - Rscript -e "install.packages('covr'); covr::codecov()"
 